### PR TITLE
smaller const definitions

### PR DESCRIPTION
**Pull request by llogiq**
Revisiting the const definitions, I found a way to make them both just a bit faster again *and* smaller / more elegant. This way, we don't even need to use Add or Shl, the definitions are now completely self-contained.

### CODE REVIEW

**Comment by paholg** [comment]
This is quite clever, I like it very much. No reason to switch to a script to make it or use a macro (unless we want to define many more constants).

**Comment by paholg** [comment]
We could also do this anywhere we use `Shl<B1>` in our operators, which I think is at least a couple places.

**Comment by llogiq** [comment]
I think we may want to define just a few more constants, e.g. `U1000 = UInt<UInt<UInt<U125, B0>, B0, B0>`. I'll push a PR to do this and replace `Shl<B1>` where I find it.

**Comment by paholg** [comment]
You might as well go ahead, I don't see anywhere they overlap.

I was also thinking that we might want to change from the const_uints.rs file to a consts directory, which will have a uint, int, and whatever else modules.

**Comment by llogiq** [comment]
Ok, I'll do that, too.

**Comment by paholg** [comment]
Actually I can do that PR now anyway.

**Pull request merged**
