### PR TITLE
faster uint consts

### PR DESCRIPTION
**Pull request by llogiq**
Using `Shl` instead of repeated `Add`s appears to be quite beneficial to our compile times. With `cargo clean && time cargo test --release`:

```
Before:
real	0m11.575s
user	0m9.108s
sys 	0m0.353s

After:
real	0m5.942s
user	0m5.674s
sys 	0m0.278s
```

### CODE REVIEW

**Comment by paholg** [comment]
That makes many sense.

**Comment by llogiq** [comment]
Yeah, the increment-until-it-fits shtick is instantiating too many intermediate types that are going to be thrown away anyway.

**Comment by paholg** [comment]
Another thought would be to have a script generate the const_uints.rs file, such that no operations are needed and types are just defined as they should be.

Maybe just wait until type macros are stable and then use that.

**Comment by paholg** [comment]
Ah, here's why I didn't realize this was an issue:
```
cargo test --release  1.15s user 0.08s system 95% cpu 1.278 total
```

**Comment by llogiq** [comment]
I think you need to `cargo clean` before the test to check the actual compile time.

**Comment by paholg** [comment]
Yeah I did.

Also, that was after this fix; before it was more like 2 seconds total.

**Pull request merged**
