### PR TITLE
And and Or for Unsigned

### PR DESCRIPTION
**Pull request by llogiq**
I think this may be useful to implement other things. We also may want to add Shl and Shr to implement division (and make our constants compile faster)

### CODE REVIEW

**Comment by paholg** [comment]
Sure thing; these should all be easy enough.

I still haven't worked out the kinks with Sub (been busy with other things mostly), but once I do, everything else should be pretty straightforward (can just replicate peano code for Mul and Div), except probably Rem.

**Comment by paholg** [comment]
Oops, I didn't realize this was a pull request. I'm new to this whole managing a github repo thing.

Looks good! Only thing is two of the doc comments for Or still refer to And.

**Comment by paholg** [comment]
So I tried to fix the doc comments, and that led to me making a pull request to you.

Is that the right way to do that? It's such a small change, and only a comment so it doesn't need testing or anything.

**Comment by llogiq** [comment]
I think we shouldn't use the code from peano.rs for Mul – the bitwise representation should allow a much faster implementation based on shl and add.

**Comment by paholg** [comment]
That's fair. It was just on my mental checklist as "something I can implement without having to think".

**Pull request merged**
