### PR TITLE
Version to 1.0.0.

### LINKED ISSUE #31: Version 1.0.0
I'd like to get this to a place we can call stable soon, then we can start telling people to use it. Also I'd like to use it for dimensioned.

I think we're almost there. As far as I can tell, the only operator we're missing is `Rem`, which we can add to the division code already there easily enough. I should have time to do that today.

Adding the quickcheck / compiletest stuff would go a long way to ensuring that our code does what we think it does.

I really can't think of anything (other than possibly fixing bugs) that we might want to implement that would cause breaking changes. I'd like to refactor division so it's faster, but that won't break anything.

Thoughts?

### PR DESCRIPTION
**Pull request by paholg**
Expanded README. This closes #31.

Edits welcome.

### CODE REVIEW

**Comment by llogiq** [comment]
Hooray! :+1:

**Comment by paholg** [comment]
Yeah, I was thinking that too. I'll announce on /r/rust, you announce on users.rust-lang?

**Comment by llogiq** [comment]
Ok, I'm on it.

**Comment by paholg** [comment]
Reddit post: https://www.reddit.com/r/rust/comments/3pbtgb/introducing_typenum_typelevel_numbers_in_rust/

**Pull request merged**
