### PR TITLE
Minor codestyle fixes

### PR DESCRIPTION
**Pull request by TalhaKhatri**
These are just some minor adjustments that don't change the logic of the library.
Mostly guided by clippy.

### CODE REVIEW

**Comment by TalhaKhatri** [comment]
Hey, I'd be more than glad to! Let me see what I can do.

**Comment by TalhaKhatri** [comment]
I think there are some differences in version of rustfmt being used on Travis and the one I used, since there are still differences.

**Comment by paholg** [comment]
Hey, sorry I've been mostly MIA since you did this. I have the Travis build working now, if you'd still like to get this merged.

**Comment by TalhaKhatri** [comment]
Hey! Sure, how can I help?

**Comment by paholg** [comment]
Hey, sorry again, I guess I failed to respond to you, and then have not really had the energy to look at this repo.

If there are still changes in this PR that you feel would have value, then feel free to re-open this PR, but it seems that code has drifted enough that I am going to close it for now.

**Pull request closed without merging**
