### PR TITLE
added xor and shl for uints

### PR DESCRIPTION
**Pull request by llogiq**
Unfortunately I'm doing something wrong in Shl. @paholg Could you have a look at it?

Once that works, I believe our constants could be quite a bit shorter.

### CODE REVIEW

**Comment by llogiq** [comment]
It may well be that the problem stems from #2

**Comment by paholg** [comment]
I think you're right.

I can't see anything wrong with your `Shl` implementation, but I'm fairly certain that 1 - 1 evaluates to `UInt<UInt<UTerm, B0>, B0>`, (or something like it), so it never hits the base case and the recursion never ends.

I've been busy, but I'll try to work on subtraction today or tomorrow, or you're welcome to take a look at it.

**Comment by llogiq** [comment]
Sub for uint is problematic anyway, because we cannot wrap around. What should the correct result be if one subtracts `UInt<UTerm, B1>` from `UTerm`?

**Comment by paholg** [comment]
I would think that the correct result for `Uterm` - `UInt<Uterm, B1>` is a compile error.

**Pull request merged**
