### PR TITLE
implement `Not` for `Unsigned` numbers

### PR DESCRIPTION
**Pull request by pittma**
Hi all!

I'm hacking on a thing that I need a `Not` implementation for; this one seems to work okay, thought I'd upstream it.

Thanks for all your work on `typenum`!

### CODE REVIEW

**Comment by pittma** [comment]
Hi all!

I believe the failed build here is spurious. It appears to only be the 2018 version of Rust which has failed and for a reason unrelated to this PR, namely, Travis is having trouble installing `cargo-clippy` for Rust 2018.

**Comment by mullr** [comment]
Any chance of getting this merged? I just ran into a place where I need it, as well.

**Comment by paholg** [comment]
Hey, sorry for the delayed response.

Can I ask how you're using this? I initially decided against implementing `Not` because its behavior would be very different than using it for normal unsigned integers.

For example, what should `not(0)` be? For a `u32`, it's `u32::MAX`, but for typenum, should it be 0? 1? infinity? I see that you've chosen 0, but that means there's an `N` where `not(N) == N`, which is pretty weird.

Also, `not(not(N)) != N`, which is very strange.

By notting a number, you lose information, and without some fixed-size type in typenum where it could behave like it does normally, I don't think it makes sense to include.

**Comment by pittma** [comment]
Hey! No worries!

I was using it to do type-level operations on hardware registers. `Not` was used on a register field's mask when making modifications to a register. It worked in our case because the mask was always of a fixed-width; however what you're saying makes total sense, and I agree, it results in unexpected behavior. Please feel free to close this.

**Pull request closed without merging**
