### PR TITLE
Sub

### PR DESCRIPTION
**Pull request by llogiq**
I think this should fix the subtraction issue.

### CODE REVIEW

**Comment by paholg** [comment]
I hadn't thought about how much specialization helps us; knowing it's coming makes me feel better about making something crappy that works, so I may just do my O(N^2) implementation and call it good enough for now.

**Comment by llogiq** [comment]
I think there may be a better solution, if we add comparison operators - we can encode Ur < Ul in a comparison type.

**Comment by paholg** [comment]
So I pulled your sub branch, mucked with some doc comments, and pushed, and I was hoping that github would figure out that should be patched to this PR, but it didn't.

**Comment by paholg** [comment]
Got it ... needed to merge it first

**Comment by paholg** [comment]
Looking at your tests ... your shifts are working properly for arbitrary numbers.

Does this mean that subtraction is working properly and I misread your changes to it?

**Comment by llogiq** [comment]
I think it only fixes the -1 path, which is what Shl/Shr use.

**Comment by paholg** [comment]
Ah, right. Still, though, that gives me an idea ... for regular subtraction, we can just sub 1 from both operands until the right one reaches `UTerm`. That way it's still O(N).

It also lets us make an `Underflow` type for if the left one reaches `UTerm` first, if we wish, and we can just expand on it for integer subtraction.

**Pull request merged**
