### PR TITLE
Travis cargo

### PR DESCRIPTION
**Pull request by llogiq**
This uses travis-cargo to test on all rust versions and upload docs, move to travis' container-based infrastructure for faster builds.

I'd hoped I could add some actual code, but I'm short on time, so this is the least I *can* do for the project.

### CODE REVIEW

**Comment by llogiq** [comment]
I have an open issue because of the failing nightly build. We can either wait until Huon comes up with a solution, or remove nightly for now.

**Comment by paholg** [comment]
Your optional crate has a gh-pages branch, which I presume is what you use.

I have a separate repository for my github page and no gh-pages branch. The best that I can tell from looking at the `doc_upload` function in travis-cargo, it will only upload the docs to a different branch of the same repository, and I can't see a way to specify that the website is a different repository.

**Comment by llogiq** [comment]
I don't have a solution for the docs-upload, though. Why do you want them in your github.io page?

**Comment by Ryman** [comment]
fwiw, github pages for a repo will appear at `username.github.io/repo`, [example](http://nickel-org.github.io/rust-mustache), and you can set which branch is the pages branch in the repo settings (if you want to change it from master to gh-pages). A CNAME on the username/org repo should still work if you're using that :)

**Comment by paholg** [comment]
Right now, I have all github pages stuff in a separate repo because I thought it would make things cleaner.

It'll just change how I do it though, as this is a cleaner solution than my script.

**Comment by paholg** [comment]
So I merged this and made a `gh-pages` branch and travis-cargo isn't committing any docs. Am I misunderstanding what the `doc-upload` command does?

**Comment by llogiq** [comment]
I think we need to wait on the next update to be sure. And your understanding of `doc-upload` is correct.

**Pull request merged**
