### PR TITLE
Mark the Bit, Unsigned and Integer traits as 'static

### LINKED ISSUE #170: Marking `Unsigned` as `'static`
Some [bytemuck](https://docs.rs/bytemuck) traits like [`Pod`](https://docs.rs/bytemuck/1/bytemuck/trait.Pod.html) have a `'static` constraint. When implementing such traits for types having an `Unsigned` type parameter, I have to add a `'static` constraint. For example

```rust
impl <T: 'static + Unsigned> Pod for MyType<T> {}
```

Since `Unsigned` should only be implemented for internal types, and all these types are `'static`, can the `Unsigned` types be marked as `'static`?

And if the answer is yes, are there any other marker traits that should receive the same treatment?

If the answer is yes, I could write a PR.

### PR DESCRIPTION
**Pull request by tspiteri**
Closes #170.

### CODE REVIEW

**Comment by tspiteri** [comment]
While adding `'static`, I found that `Bit` and `Unsigned` both have `Copy + Default` supertraits but `Integer` does not. Does it make sense to also add `Copy + Default` to `Integer` for consistency, or was the omission intentional?

**Comment by paholg** [comment]
It was not intentional. That would be appreciated!

**Comment by tspiteri** [comment]
Done.

**Comment by paholg** [comment]
Thanks!

**Pull request merged**
